
//import java.sql.ResultSet;
//import java.sql.SQLException;
// import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noahc
 */
public class DatabaseOperationsPage extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseOperationsPage
     */
    public DatabaseOperationsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        DropTablesButton = new javax.swing.JButton();
        CreateTablesButton = new javax.swing.JButton();
        PopulateTablesButton = new javax.swing.JButton();
        QueryTablesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        BackButton.setText("Go Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        TitleLabel.setText("Database Operations (DANGER)");

        DropTablesButton.setText("Drop Tables");
        DropTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropTablesButtonActionPerformed(evt);
            }
        });

        CreateTablesButton.setText("Create Tables");
        CreateTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTablesButtonActionPerformed(evt);
            }
        });

        PopulateTablesButton.setText("Populate Tables");
        PopulateTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopulateTablesButtonActionPerformed(evt);
            }
        });

        QueryTablesButton.setText("Query Tables");
        QueryTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryTablesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(TitleLabel)
                .addGap(0, 108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DropTablesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateTablesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PopulateTablesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QueryTablesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addGap(18, 18, 18)
                .addComponent(TitleLabel)
                .addGap(34, 34, 34)
                .addComponent(DropTablesButton)
                .addGap(18, 18, 18)
                .addComponent(CreateTablesButton)
                .addGap(18, 18, 18)
                .addComponent(PopulateTablesButton)
                .addGap(18, 18, 18)
                .addComponent(QueryTablesButton)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        PayrollAdminHomePage payrollScreen = new PayrollAdminHomePage();
        payrollScreen.show();

        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DropTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropTablesButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Successfully DROPPED tables!");
//        try {
//            Statement stmt = MainClass.connection.createStatement();
//            ResultSet rs = stmt.executeQuery("DROP TABLE PAYSTUB CASCADE CONSTRAINTS");
//            if (rs != null) {
//                while (rs.next()) {
//                    System.out.println("User Found: " + rs.getString("FIRST_NAME"));
//                    
//                    MainClass.loggedInEmployee.EMPLOYEE_ID = rs.getInt("EMPLOYEE_ID");
//                    MainClass.loggedInEmployee.DEPARTMENT_ID = rs.getInt("DEPARTMENT_ID");
//                    MainClass.loggedInEmployee.FIRST_NAME = rs.getString("FIRST_NAME");
//                    MainClass.loggedInEmployee.LAST_NAME = rs.getString("LAST_NAME");
//                    MainClass.loggedInEmployee.DATE_OF_BIRTH = rs.getString("DATE_OF_BIRTH");
//                    MainClass.loggedInEmployee.SIN_NUMBER = rs.getInt("SIN_NUMBER");
//                    MainClass.loggedInEmployee.DATE_HIRED = rs.getString("DATE_HIRED");
//                    MainClass.loggedInEmployee.PAYROLL_TYPE = rs.getString("PAYROLL_TYPE");
//                    MainClass.loggedInEmployee.SALARY = rs.getDouble("SALARY");
//                    MainClass.loggedInEmployee.VAC_DAYS_TOTAL = rs.getInt("VAC_DAYS_TOTAL");
//                    MainClass.loggedInEmployee.VAC_DAYS_LEFT = rs.getInt("VAC_DAYS_LEFT");
//                    MainClass.loggedInEmployee.SICK_DAYS_TOTAL = rs.getInt("SICK_DAYS_TOTAL");
//                    MainClass.loggedInEmployee.SICK_DAYS_LEFT = rs.getInt("SICK_DAYS_LEFT");
//                    MainClass.loggedInEmployee.PERS_DAYS_TOTAL = rs.getInt("PERS_DAYS_TOTAL");
//                    MainClass.loggedInEmployee.PERS_DAYS_LEFT = rs.getInt("PERS_DAYS_LEFT");
//                    MainClass.loggedInEmployee.USERNAME = rs.getString("USERNAME");
//                    MainClass.loggedInEmployee.PASSWORD = rs.getString("PASSWORD");
//                    MainClass.loggedInEmployee.BANK_ID = rs.getInt("BANK_ID");
//                    MainClass.loggedInEmployee.BRANCH_NUMBER = rs.getInt("BRANCH_NUMBER");
//                    MainClass.loggedInEmployee.ACCOUNT_NUMBER = rs.getInt("ACCOUNT_NUMBER");
//                    MainClass.loggedInEmployee.IS_ADMIN = rs.getInt("IS_ADMIN"); 
//                    MainClass.loggedInEmployee.rs_emp = rs;              
//                    loginAllowed = true;
//                }
//            } else {
//                System.out.println("Query Null");
//            }
//        } catch (SQLException e) {
//            System.out.print("Failed to Execute Statement: ");
//            System.out.println(e.getErrorCode());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_DropTablesButtonActionPerformed

    private void PopulateTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopulateTablesButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Successfully POPULATED tables!");
    }//GEN-LAST:event_PopulateTablesButtonActionPerformed

    private void CreateTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTablesButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Successfully CREATED tables!");
    }//GEN-LAST:event_CreateTablesButtonActionPerformed

    private void QueryTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueryTablesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QueryTablesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseOperationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseOperationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseOperationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseOperationsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseOperationsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CreateTablesButton;
    private javax.swing.JButton DropTablesButton;
    private javax.swing.JButton PopulateTablesButton;
    private javax.swing.JButton QueryTablesButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
